[api]
host = "0.0.0.0"
port = 8080

[aws]
region_name = "ap-northeast-1"
endpoint_url = "http://localhost:4566"
access_key_id = "x"
secret_access_key = "x"

[stream]
journal_table_name = "journal"
max_item_count = 100

[database]
url = "mysql://ceer:ceer@localhost:3306/ceer"